# Generated by Django 5.0 on 2023-12-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_shop', '0002_item_currency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discount',
            name='discount_check_percent_between_0_and_100',
        ),
        migrations.RemoveConstraint(
            model_name='tax',
            name='tax_check_percent_between_0_and_100',
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percent',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(check=models.Q(('percent__gt', 0), ('percent__lt', 10000)), name='discount_check_percent_between_0_and_10000'),
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.CheckConstraint(check=models.Q(('percent__gt', 0), ('percent__lt', 10000)), name='tax_check_percent_between_0_and_10000'),
        ),
    ]
