# Generated by Django 5.0 on 2023-12-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_shop', '0004_orderitem_remove_order_items_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tax',
            name='tax_check_percent_between_0_and_10000',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='percent',
        ),
        migrations.AddField(
            model_name='tax',
            name='country',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='display_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='inclusive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='jurisdiction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=4, default=10, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='stripe_id',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.CheckConstraint(check=models.Q(('percentage__gt', 0), ('percentage__lt', 100)), name='tax_check_percentage_between_0_and_100'),
        ),
    ]
