# Generated by Django 5.0 on 2023-12-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_shop', '0005_remove_tax_tax_check_percent_between_0_and_10000_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='jurisdiction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='stripe_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
