# Generated by Django 5.0 on 2023-12-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_shop', '0006_alter_tax_country_alter_tax_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='currency',
            field=models.CharField(db_index=True, default='usd', max_length=3),
            preserve_default=False,
        ),
    ]
