# Generated by Django 5.0 on 2023-12-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_shop', '0007_tax_currency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discount',
            name='discount_check_percent_between_0_and_10000',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='percent',
        ),
        migrations.AddField(
            model_name='discount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(check=models.Q(('percentage__gt', 0), ('percentage__lt', 100)), name='discount_check_percentage_between_0_and_10000'),
        ),
    ]
